trigger:
  branches:
    include:
    - develop
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: 'aks'
  imageRepository: 'devGo'
  containerRegistry: 'henryDev.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

steps:
  - task: CmdLine@2
    displayName: 'Custom git clone'
    inputs:
      script: |
        echo 'Cloning into sources folder at: $(Build.SourcesDirectory)'
        git clone https://github.com/azxcvba82/goDev --branch develop
        exit
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    
  - task: Docker@2
    displayName: Build and push to Azure container registry
    inputs:
      command: buildAndPush
      buildContext: .
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(Build.BuildNumber)      
