apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go-dev-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-dev-api
  template:
    metadata:
      labels:
        app: go-dev-api
    spec:
      containers:
      - name: go-dev-api
        image: docker.io/azxcvba81/henry_dev_go:latest
        env:
        - name: SQLCONNECTSTRING
          valueFrom:
            secretKeyRef:
              name: sql-config
              key: sqlconnectstring
              optional: false
        - name: SQLCONNECTSTRINGREAD
          valueFrom:
            secretKeyRef:
              name: sql-config
              key: sqlconnectstringread
              optional: false
        - name: REDISPASSWORD
          valueFrom:
            secretKeyRef:
              name: cache-config
              key: cachepassword
              optional: false
        - name: REDISADDRESS
          valueFrom:
            secretKeyRef:
              name: cache-config
              key: cacheaddress
              optional: false
        - name: GITHUBHASHVALUE
          value: ${{ github.sha }}
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Exists"
        effect: "NoSchedule"
