apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go-dev-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-dev-api
  template:
    metadata:
      labels:
        app: go-dev-api