info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: get users in a group
      parameters:
      - description: json
        in: body
        name: login
        required: true
        schema:
          type: object
      responses:
        "200":
          description: ok
        "500":
          description: error
swagger: "2.0"
