info:
  contact: {}
  description: This is a api web server.
  title: Swagger API
  version: "1.0"
paths:
  /allAlbumType:
    get:
      description: allAlbumType load
      responses:
        "200":
          description: ok
        "500":
          description: error
      tags:
      - Search
  /allkind:
    get:
      description: allkind load
      responses:
        "200":
          description: ok
        "500":
          description: error
      tags:
      - Kind
  /api/addPlayLists:
    get:
      description: addPlayLists load
      parameters:
      - description: string valid
        in: query
        name: productId
        required: true
        type: string
      responses:
        "200":
          description: ok
        "500":
          description: error
      security:
      - securityDefinitions.apikey BearerAuth: []
      - BearerAuth: []
      tags:
      - Album
  /api/deletePlayLists:
    get:
      description: deletePlayLists load
      parameters:
      - description: string valid
        in: query
        name: productId
        required: true
        type: string
      responses:
        "200":
          description: ok
        "500":
          description: error
      security:
      - securityDefinitions.apikey BearerAuth: []
      - BearerAuth: []
      tags:
      - Album
  /api/getAccountFromJWT:
    get:
      consumes:
      - application/json
      description: getAccountFromJWT
      parameters:
      - description: token
        in: path
        name: user
        required: true
        type: string
      responses:
        "200":
          description: ok
        "500":
          description: error
      security:
      - securityDefinitions.apikey BearerAuth: []
      - BearerAuth: []
      tags:
      - Token
  /api/getPlayListByAccount:
    get:
      description: getPlayListByAccount load
      responses:
        "200":
          description: ok
        "500":
          description: error
      security:
      - securityDefinitions.apikey BearerAuth: []
      - BearerAuth: []
      tags:
      - Album
  /getAlbumById:
    get:
      description: getAlbumById load
      parameters:
      - description: string valid
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: ok
        "500":
          description: error
      tags:
      - Album
  /getAlbumsByKindId:
    get:
      description: getAlbumsByKindId load
      parameters:
      - description: string valid
        in: query
        name: kindId
        required: true
        type: string
      responses:
        "200":
          description: ok
        "500":
          description: error
      tags:
      - Album
  /getProductsByAlbumId:
    get:
      description: getProductsByAlbumId load
      parameters:
      - description: string valid
        in: query
        name: albumId
        required: true
        type: string
      responses:
        "200":
          description: ok
        "500":
          description: error
      tags:
      - Album
  /getProductsByProductName:
    get:
      description: getProductsByProductName load
      parameters:
      - description: string valid
        in: query
        name: name
        type: string
      - description: string valid
        in: query
        name: albumName
        type: string
      - description: string valid
        in: query
        name: singer
        type: string
      - description: string valid
        in: query
        name: group
        type: string
      - description: string valid
        in: query
        name: composer
        type: string
      - description: int valid
        in: query
        name: type
        type: integer
      responses:
        "200":
          description: ok
        "500":
          description: error
      tags:
      - Search
  /login:
    post:
      consumes:
      - application/json
      description: login user
      parameters:
      - description: json
        in: body
        name: login
        required: true
        schema:
          type: object
      responses:
        "200":
          description: ok
        "500":
          description: error
      tags:
      - Token
  /mainActivities:
    get:
      description: mainActivities load
      responses:
        "200":
          description: ok
        "500":
          description: error
      tags:
      - Homepage
  /mainAlbums:
    get:
      description: mainAlbums load
      responses:
        "200":
          description: ok
        "500":
          description: error
      tags:
      - Homepage
  /signup:
    post:
      consumes:
      - application/json
      description: create user
      parameters:
      - description: json
        in: body
        name: signup
        required: true
        schema:
          type: object
      responses:
        "200":
          description: ok
        "500":
          description: error
      tags:
      - Token
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
