name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ master ]
    
env:
  RESOURCE_GROUP: "devRG"
  CLUSTER_NAME: "henry-aks-dev"

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
    steps:
        # Logs in with your Azure credentials
      - 
        name: Azure login
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      -
        # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
        name: Get K8s context
        uses: azure/aks-set-context@v2.0
        with:
            resource-group: ${{ env.RESOURCE_GROUP }}
            cluster-name: ${{ env.CLUSTER_NAME }}


      -
        # Deploys application based on given manifest file
        name: Deploys application
        uses: Azure/k8s-deploy@v3.1
        with:
            action: deploy
            manifests: |
            images: |
              docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/henry_dev_go:latest

    
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 
           ${{ secrets.DOCKER_HUB_USERNAME }}/henry_dev_go:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/henry_dev_go:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/henry_dev_go:buildcache,mode=max
          

